site_name: OSG Education
site_url: https://opensciencegrid.github.io/education/
repo_url: https://github.com/opensciencegrid/education/
theme:
  name: windmill

extra:
  article_nav_top: false

extra_css:
  - css/extra.css

pages:
  - OSG Education: index.md
  - User School 2017:
    - Home: user-school/2017/index.md

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
