site_name: OSG Education
site_url: https://opensciencegrid.github.io/education/
repo_name: null
repo_url: null
theme:
  name: windmill

extra:
  article_nav_top: false

extra_css:
  - css/extra.css

# Suppress weird JavaScript problems with development server
extra_javascript: []

pages:
  - OSG Education:                  index.md
  - User School 2017:
    - Home:                         user-school/2017/index.md
    - Logistics:
      - General information:        user-school/2017/logistics/index.md
      - Visa requirements:          user-school/2017/logistics/personal-info.md
      - Travel planning:            user-school/2017/logistics/travel.md
      - Hotel information:          user-school/2017/logistics/hotel.md
      - Local transportation:       user-school/2017/logistics/local-transportation.md
      - School location:            user-school/2017/logistics/location.md
      - Meals at the School:        user-school/2017/logistics/meals.md
      - Fun in Madison:             user-school/2017/logistics/fun.md
      - Wednesday activities:       user-school/2017/logistics/wednesday-activities.md
      - Reimbursements:             user-school/2017/logistics/reimbursements.md
    - Curriculum:
      - High-level overview:        user-school/2017/curriculum/overview.md
      - Detailed schedule:          user-school/2017/curriculum/detailed-schedule.md
      - Evening sessions:           user-school/2017/curriculum/evening-sessions.md
      - Final assignment:           user-school/2017/curriculum/assignment.md
    - Materials:
      - All materials:              user-school/2017/materials/index.md
      - Set up OSG Connect:         user-school/2017/materials/connect.md
      - Day 1 Exercises:
        - 1.1. Log in:              user-school/2017/materials/day1/part1-ex1-login.md
        - 1.2. Commands:            user-school/2017/materials/day1/part1-ex2-commands.md
        - 1.3. Run jobs:            user-school/2017/materials/day1/part1-ex3-jobs.md
        - 1.4. Log files:           user-school/2017/materials/day1/part1-ex4-logs.md
        - 1.5. Resource needs:      user-school/2017/materials/day1/part1-ex5-request.md
        - 1.6. Remove jobs:         user-school/2017/materials/day1/part1-ex6-remove.md
        - 1.7. (opt) Compiling:     user-school/2017/materials/day1/part1-ex7-compile.md
        - 2.1. condor_q:            user-school/2017/materials/day1/part2-ex1-queue.md
        - 2.2. condor_status:       user-school/2017/materials/day1/part2-ex2-status.md
        - 2.3. I/O files:           user-school/2017/materials/day1/part2-ex3-files.md
        - 2.4. queue N:             user-school/2017/materials/day1/part2-ex4-queue-n.md
        - 2.5. queue matching:      user-school/2017/materials/day1/part2-ex5-queue-matching.md
        - 2.6. queue from:          user-school/2017/materials/day1/part2-ex6-queue-from.md
        - 3.1. Retries:             user-school/2017/materials/day1/part3-ex1-job-retry.md
        - 3.2. Mandelbrot set:      user-school/2017/materials/day1/part3-ex2-mandelbrot.md
        - 3.3. Simple DAG:          user-school/2017/materials/day1/part3-ex3-simple-dag.md
        - 3.4. More complex DAG:    user-school/2017/materials/day1/part3-ex4-complex-dag.md
        - 4.1. Failed DAG jobs:     user-school/2017/materials/day1/part4-ex1-failed-dag.md
        - 4.2. DAG variables:       user-school/2017/materials/day1/part4-ex2-dag-vars.md
        - 4.3. DAG SPLICE:          user-school/2017/materials/day1/part4-ex3-dag-splice.md
        - 4.4. Bonus challenges:    user-school/2017/materials/day1/part4-ex4-challenges.md
      - Day 2 Exercises:
        - 1.1. Refresher:           user-school/2017/materials/day2/part1-ex1-submit-refresher.md
        - 1.2. Submit host:         user-school/2017/materials/day2/part1-ex2-login-scp.md
        - 1.3. Jobs in OSG:         user-school/2017/materials/day2/part1-ex3-submit-osg.md
        - 2.1. Hardware in OSG:     user-school/2017/materials/day2/part2-ex1-hardware-diffs.md
        - 2.2. Software in OSG:     user-school/2017/materials/day2/part2-ex2-software-diffs.md
        - 3.1. Troubleshooting:     user-school/2017/materials/day2/part4-ex1-troubleshooting.md
      - Day 3 Exercises:
        - 1.1. Compiling programs:  user-school/2017/materials/day3/part1-ex1-compiling.md
        - 1.2. Pre-compiled binary: user-school/2017/materials/day3/part1-ex2-precompiled.md
        - 1.3. Wrapper script:      user-school/2017/materials/day3/part1-ex3-wrapper.md
        - 1.4. Pre-packaging code:  user-school/2017/materials/day3/part1-ex4-prepackaged.md
        - 1.5. (opt) Arguments:     user-school/2017/materials/day3/part1-ex5-arguments.md
        - 2.1. Using MATLAB:        user-school/2017/materials/day3/part2-ex1-matlab.md
        - 2.2. Packaging Python:    user-school/2017/materials/day3/part2-ex2-python-built.md
        - 2.3. Installing Python:   user-school/2017/materials/day3/part2-ex3-python-install.md
        - 2.4. (opt) Containers:    user-school/2017/materials/day3/part2-ex4-containers.md
      - Day 4 Exercises:
        - 1.1. OSG Connect:         user-school/2017/materials/day4/part1-ex1-connect-intro.md
        - 1.2. Quickstart:          user-school/2017/materials/day4/part1-ex2-connect-quickstart.md
        - 1.3. Software modules:    user-school/2017/materials/day4/part1-ex3-connect-modules.md
        - 1.4. (opt) Singularity:   user-school/2017/materials/day4/part1-ex4-singularity.md
        - 2.1. Data requirements:   user-school/2017/materials/day4/part2-ex1-data-needs.md
        - 2.2. HTCondor transfers:  user-school/2017/materials/day4/part2-ex2-file-transfer.md
        - 2.3. Splitting big data:  user-school/2017/materials/day4/part2-ex3-blast-split.md
        - 3.1. Web proxies:         user-school/2017/materials/day4/part3-ex1-blast-proxy.md
        - 3.2. StashCache Ⅰ:        user-school/2017/materials/day4/part3-ex2-stashcache-shared.md
        - 3.3. StashCache Ⅱ:        user-school/2017/materials/day4/part3-ex3-stashcache-unique.md
        - 4.1. Shared FS input:     user-school/2017/materials/day4/part4-ex1-input.md
        - 4.2. Shared FS output:    user-school/2017/materials/day4/part4-ex2-output.md
      - Day 5 Exercises:
        - 1.1. Learn workflow:      user-school/2017/materials/day5/part1-ex1-science-intro.md
        - 1.2. Plan workflow:       user-school/2017/materials/day5/part1-ex2-plan-workflow.md
        - 1.3. Execute workflow:    user-school/2017/materials/day5/part2-ex1-execute-workflow.md
        - 1.4. (opt) Tune workflow: user-school/2017/materials/day5/part2-ex2-workflow-tuning.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
