site_name: OSG Education
site_url: https://opensciencegrid.github.io/education/
repo_name: null
repo_url: null
theme:
  name: windmill

extra:
  article_nav_top: false

extra_css:
  - css/extra.css

pages:
  - OSG Education: index.md
  - User School 2017:
    - Home: user-school/2017/index.md
    - Logistics:
      - General information:  user-school/2017/logistics/index.md
      - Visa requirements:    user-school/2017/logistics/personal-info.md
      - Travel planning:      user-school/2017/logistics/travel.md
      - Hotel information:    user-school/2017/logistics/hotel.md
      - Local transportation: user-school/2017/logistics/local-transportation.md
      - School location:      user-school/2017/logistics/location.md
      - Meals at the School:  user-school/2017/logistics/meals.md
      - Fun in Madison:       user-school/2017/logistics/fun.md
      - Reimbursements:       user-school/2017/logistics/reimbursements.md
    - Curriculum:
      - High-level overview:  user-school/2017/curriculum/overview.md
      - Detailed schedule:    user-school/2017/curriculum/detailed-schedule.md
      - Evening sessions:     user-school/2017/curriculum/evening-sessions.md
      - Final assignment:     user-school/2017/curriculum/assignment.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
