site_name: OSG Education
site_url: https://opensciencegrid.github.io/education/
repo_url: https://github.com/opensciencegrid/education/
theme:
  name: windmill

extra:
  article_nav_top: false

extra_css:
  - css/extra.css

pages:
  - OSG Education: index.md
  - User School 2017:
    - Home: user-school/2017/index.md
    - Logistics:
      - General information:  user-school/2017/logistics/index.md
      - Visa requirements:    user-school/2017/logistics/personal-info.md
      - Travel planning:      user-school/2017/logistics/travel.md
      - Hotel information:    user-school/2017/logistics/hotel.md
      - Local transportation: user-school/2017/logistics/local-transportation.md
      - School location:      user-school/2017/logistics/location.md
      - Meals at the School:  user-school/2017/logistics/meals.md
      - Fun in Madison:       user-school/2017/logistics/fun.md
      - Reimbursements:       user-school/2017/logistics/reimbursements.md

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
